blank_issues_enabled: false
contact_links:
  - name: Docs
    url: https://www.checklyhq.com/product/terraform-provider/
    about: If you need help, you can start checking out our documentation
  - name: API Reference
    url: https://developers.checklyhq.com
    about: The API is also a great way to help you debugging issues
  - name: Terraform Provider Registry
    url: https://registry.terraform.io/providers/checkly/checkly/latest/docs
    about: The official Terraform registry contains all the basic information about the provider resources
  - name: Questions
    url: https://github.com/checkly/terraform-provider-checkly/discussions
    about: Ask questions and discuss with other community members